#SPDX-License-Identifier: MIT-0
---
- name: Create oxidized system user
  ansible.builtin.user:
    name: "{{ oxidized_user }}"
    create_home: yes
    home: "{{ oxidized_home }}"
    system: yes
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ oxidized_required_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Install Oxidized gem
  community.general.gem:
    name: oxidized
    state: present
    user_install: no
  become: true

- name: Install Oxidized web
  community.general.gem:
    name: oxidized-web
    state: present
    user_install: no
  become: true
  when: oxidized_install_web

- name: Install Oxidized script
  community.general.gem:
    name: oxidized-script
    state: present
    user_install: no
  become: true
  when: oxidized_install_script

- name: Create config file for Oxidized
  ansible.builtin.template:
    src: config.j2
    dest: "{{ oxidized_home }}/.config/oxidized/config"
    owner: "{{ oxidized_user }}"
    group: "{{ oxidized_group }}"
    mode: '0600'
  become_user: "{{ oxidized_user }}"

# Create empty csv file for default csv file
- name: Create empty router.db
  ansible.builtin.file:
    path: "{{ oxidized_home }}/.config/oxidized/router.db"
    state: touch
    owner: "{{ oxidized_user }}"
    group: "{{ oxidized_group }}"
    mode: '0650'

- name: Create systemd service file for Oxidized
  ansible.builtin.template:
    src: oxidized.service.j2
    dest: /etc/systemd/system/oxidized.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: 
    - enable oxidized service
